name: scraper_docker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - ipykernel
  - notebook
  - jupyterlab
  - pip:
    - selenium==4.15.2
    - webdriver-manager==4.0.1
    - opencv-python
    - pytesseract
    - python-dotenv
    - pillow
    - requests
    - charset-normalizer
platforms:
  - linux-64
  - linux-aarch64